import { Inter } from "next/font/google";
import "./globals.css";
import Firstnav from "./components/firstnav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "test app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Firstnav></Firstnav>
        {children}
      </body>
    </html>
  );
}
